---

- name: Installing nginx and put index.php

  hosts: webservers
  remote_user: ubuntu
  become: true

  tasks:
    - name: Upgrading all apt packages on webservers group
      become: true	
      apt: 
        upgrade: dist 
        force_apt_get: yes

    - name: installing nginx on webservers group
      become: true
      apt:
        name: nginx
        state: latest
 
    - name: installing php7.4-fpm on webservers group
      become: true
      apt: 
        name: php7.4-fpm
        state: present
 
    - name: transfering index.php file to webservers group
      copy:
        src: index.php
        dest: /var/www/html/index.php
 
    - name: nginx configuration file 
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/nginx.conf

      notify:
        -restart php7.4-fpm
        -reload nginx        

- hosts:  haproxy
  become: true 
        
  tasks:
    - name: Installing HAproxy
      apt: 
        name: haproxy 
        state:  present
    
    - name: Transfering HAproxy Config file 
      template:
        src:  haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        
    - name: Running the HAproxy
      service:  
        name: haproxy
        state:  restarted
