---

- name: Installing nginx and put index.php

  hosts: webservers
  remote_user: ubuntu
  become: true

  tasks:
    - name: Upgrading all apt packages on webservers group
      become: true	
      apt: 
        upgrade: dist 
        force_apt_get: yes

    - name: installing nginx on webservers group
      become: true
      apt:
        name: nginx
        state: present
 
    - name: installing php7.4-fpm on webservers group
      become: true
      apt:
        update_cache: yes
        name: ['php7.4-fpm' , 'php']
        state: latest
 
    - name: transfering index.php file to webservers group
      copy:
        src: index.php
        dest: /var/www/html/index.php
 
    - name: nginx configuration file 
      copy: 
        src: nginx.conf 
        dest: /etc/nginx/sites-available/default
    
        
    - name: restart nginx
      service:
        name: nginx
        state: restarted        

- name: Installing Haproxy load balancer  
  
  hosts:  haproxy
  become: true 
        
  tasks:
    - name: Installing Haproxy
      apt: 
        name: haproxy 
        state:  present
    
    - name: Transfering haproxy.cfg 
      template:
        src:  haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        
    - name: Running the HAproxy
      service:  
        name: haproxy
        state:  restarted
